# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Install build backend and dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libffi-dev build-essential && \
    pip install --no-cache-dir hatchling && \
    apt-get purge -y --auto-remove gcc build-essential && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY pyproject.toml ./
COPY uv.lock ./
COPY src ./src
COPY README.md ./

# Install package
RUN pip install --no-cache-dir .

# Set default environment variable placeholder
ENV JUHE_EXCHANGE_API_KEY=""

# Expose stdio
ENTRYPOINT ["jexchange-mcp-server"]
